# uncompyle6 version 3.9.0
# Python bytecode version base 3.7.0 (3394)
# Decompiled from: Python 3.7.16 (default, May 16 2023, 11:05:37) 
# [Clang 13.0.0 (clang-1300.0.29.30)]
# Embedded file name: T:\InGame\Gameplay\Scripts\Server\sims\genealogy_relgraph_enums.py
# Compiled at: 2022-02-09 13:21:47
# Size of source mod 2**32: 2163 bytes
import enum

class SimRelBitShift(enum.Int, export=False):
    SIMRELEBITSHIFT_MOTHER = 0
    SIMRELEBITSHIFT_FATHER = 1
    SIMRELEBITSHIFT_DAUGHTER = 2
    SIMRELEBITSHIFT_SON = 3
    SIMRELEBITSHIFT_WIFE = 4
    SIMRELEBITSHIFT_HUSBAND = 5
    SIMRELEBITSHIFT_FIANCEE = 6
    SIMRELEBITSHIFT_FIANCE = 7
    SIMRELEBITSHIFT_MAX = 7
    SIMRELEBITSHIFT_PREEXISTING = 31


class SimRelBitFlags(enum.IntFlags, export=False):
    SIMRELBITFLAG_NONE = 0
    SIMRELBITFLAG_MOTHER = 1 << SimRelBitShift.SIMRELEBITSHIFT_MOTHER
    SIMRELBITFLAG_FATHER = 1 << SimRelBitShift.SIMRELEBITSHIFT_FATHER
    SIMRELBITFLAG_DAUGHTER = 1 << SimRelBitShift.SIMRELEBITSHIFT_DAUGHTER
    SIMRELBITFLAG_SON = 1 << SimRelBitShift.SIMRELEBITSHIFT_SON
    SIMRELBITFLAG_WIFE = 1 << SimRelBitShift.SIMRELEBITSHIFT_WIFE
    SIMRELBITFLAG_HUSBAND = 1 << SimRelBitShift.SIMRELEBITSHIFT_HUSBAND
    SIMRELBITFLAG_FIANCEE = 1 << SimRelBitShift.SIMRELEBITSHIFT_FIANCEE
    SIMRELBITFLAG_FIANCE = 1 << SimRelBitShift.SIMRELEBITSHIFT_FIANCE
    SIMRELBITFLAG_PREEXISTING = 1 << SimRelBitShift.SIMRELEBITSHIFT_PREEXISTING
    SIMRELBITS_MALE = SIMRELBITFLAG_FATHER | SIMRELBITFLAG_SON | SIMRELBITFLAG_HUSBAND | SIMRELBITFLAG_FIANCE
    SIMRELBITS_FEMALE = SIMRELBITFLAG_MOTHER | SIMRELBITFLAG_DAUGHTER | SIMRELBITFLAG_WIFE | SIMRELBITFLAG_FIANCEE
    SIMRELBITS_CHILD = SIMRELBITFLAG_DAUGHTER | SIMRELBITFLAG_SON
    SIMRELBITS_PARENT = SIMRELBITFLAG_MOTHER | SIMRELBITFLAG_FATHER
    SIMRELBITS_SPOUSE = SIMRELBITFLAG_WIFE | SIMRELBITFLAG_HUSBAND
    SIMRELBITS_FIANCE = SIMRELBITFLAG_FIANCE | SIMRELBITFLAG_FIANCEE
    SIMRELBITS_ALL = SIMRELBITS_CHILD | SIMRELBITS_PARENT | SIMRELBITS_SPOUSE | SIMRELBITS_FIANCE